services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    hostname: jobmanager
    container_name: jobmanager
    depends_on:
      - iceberg-rest
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./:/data/
    networks:
      - flink-seaweedfs
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_ENDPOINT=http://seaweedfs:9000
      - AWS_REGION=us-east-1
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.flamegraph.enabled: true
        s3.access-key: admin
        s3.secret-key: password
        s3.endpoint: http://seaweedfs:9000
        s3.path.style.access: true

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./:/data/
    networks:
      - flink-seaweedfs
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_ENDPOINT=http://seaweedfs:9000
      - AWS_REGION=us-east-1
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        s3.access-key: admin
        s3.secret-key: password
        s3.endpoint: http://seaweedfs:9000
        s3.path.style.access: true

  iceberg-rest:
    image: apache/iceberg-rest-fixture:latest
    container_name: iceberg-rest
    depends_on:
      - aws-cli
    ports:
      - "8181:8181"
    restart: on-failure
    networks:
      - flink-seaweedfs
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://seaweedfs:9000
      CATALOG_S3_ACCESS__KEY__ID: admin
      CATALOG_S3_SECRET__ACCESS__KEY: password
      CATALOG_S3_PATH__STYLE__ACCESS: "true"
      CATALOG_S3_REGION: us-east-1

  seaweedfs:
    image: chrislusf/seaweedfs:4.06
    container_name: seaweedfs
    ports:
      - "9333:9333"
      - "8888:8888"
      - "9000:9000"
      - "8080:8080"
    command: server -s3 -s3.port=9000 -s3.config=/etc/seaweedfs/s3.json -master.port=9333 -volume.port=8080 -filer -filer.port=8888
    configs:
      - source: s3-config
        target: /etc/seaweedfs/s3.json
    networks:
      - flink-seaweedfs

  aws-cli:
    image: amazon/aws-cli:latest
    container_name: aws-cli
    depends_on:
      - seaweedfs
    networks:
      - flink-seaweedfs
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_ENDPOINT_URL=http://seaweedfs:9000
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (aws s3 ls --endpoint-url http://seaweedfs:9000 2>/dev/null) do echo '...waiting for S3...' && sleep 1; done;
      aws s3 mb s3://warehouse --endpoint-url http://seaweedfs:9000 2>/dev/null || true;
      tail -f /dev/null
      "

networks:
  flink-seaweedfs:
    name: flink-seaweedfs

configs:
  s3-config:
    content: |
      { "identities": [ { "name": "anonymous", "credentials": [ { "accessKey": "admin", "secretKey": "password" } ], "actions": [ "Admin", "Read", "Write" ] } ] }
